config/routes.rb
Rails.application.routes.draw do
  resources :logs, only: [:index]
  resources :casts
  resources :actors
  resources :comments
  resources :movies
  post 'movies/add_actor_to_cast', to: 'movies#add_actor_to_cast', as: :add_actor_to_cast
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'movies#index'
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :name, :email, :birth_date, presence: true
  validates :email, uniqueness: true

  has_many :casts, dependent: :destroy
  has_many :movies, through: :casts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cast.rb
class Cast < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_update :save_to_logs

  validates :text, presence: true
  belongs_to :movie

  scope :not_approved, -> { where(status: false) }
  scope :approved, -> { where(status: true) }

  has_one :log

  def save_to_logs
    Log.create(approved_date: Time.now.strftime('%d-%m-%Y'), comment_id: id) if log.blank?
  end
end

app/models/log.rb
class Log < ApplicationRecord
  validates :approved_date, presence: true
  belongs_to :comment
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :release_year, presence: true
  validates :title, uniqueness: true
  validates :release_year, comparison: { less_than: Time.now.strftime('%Y').to_i, greater_than: 1900 }

  has_many :comments, dependent: :destroy
  has_many :casts, dependent: :destroy
  has_many :actors, through: :casts
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[show edit update destroy]

  def index
    @actors = Actor.all
  end

  def show; end

  def new
    @actor = Actor.new
  end

  def edit; end

  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to actor_url(@actor), notice: 'Ator foi criado com sucesso.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to actor_url(@actor), notice: 'Ator foi atualizado com sucesso' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Ator foi deletado com sucesso' }
    end
  end

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:name, :birth_date, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_action :set_cast, only: %i[show edit update destroy]

  def index
    @casts = Cast.all
  end

  def show; end

  def new
    @cast = Cast.new
  end

  def edit; end

  def create
    @cast = Cast.new(cast_params)

    respond_to do |format|
      if @cast.save
        format.html { redirect_to cast_url(@cast), notice: 'Cast was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cast.update(cast_params)
        format.html { redirect_to cast_url(@cast), notice: 'Cast was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cast.destroy

    respond_to do |format|
      format.html { redirect_to casts_url, notice: 'Cast was successfully destroyed.' }
    end
  end

  private

  def set_cast
    @cast = Cast.find(params[:id])
  end

  def cast_params
    params.require(:cast).permit(:movie_id, :actor_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  def index
    @comments = Comment.not_approved
  end

  def show; end

  def new
    @comment = Comment.new
    @movies = Movie.all
  end

  def edit; end

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comments_path, notice: 'Comentário foi criado com sucesso.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comments_path, notice: 'Comentário foi aprovado com sucesso.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comentário foi deletado com sucesso.' }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text, :status, :movie_id)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
   
  def index
    @logs = Log.all
  end

  def show; 
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[show edit update destroy add_actor_to_cast]

  def index
    @movies = Movie.all
  end

  def show
    movie_actors_ids = @movie.actors.pluck(:id)
    @available_actors = Actor.where.not(id: movie_actors_ids)
  end

  def new
    @movie = Movie.new
  end

  def edit; end

  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: 'Movie was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: 'Movie was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
    end
  end

  def add_actor_to_cast
    respond_to do |format|
      if Cast.create(movie_id: @movie.id, actor_id: params[:actor_id])
        format.html { redirect_to movie_url(@movie), notice: 'Ator adicionado com sucesso' }
      else
        format.html { render :show, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :release_year, :actor_id)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/_actor.html.erb
<div id="<%= dom_id actor %>">
  <p>
    <strong>Nome:</strong>
    <%= actor.name %>
  </p>
  <ul>
    <li>
      <p>
        <strong>Ano de Nascimento:</strong>
        <%= actor.birth_date %>
      </p> 
    </li>
    <li>
      <p>
        <strong>Email:</strong>
        <%= actor.email %>
      </p>
    </li>
  </ul>
  <% if actor.movies.present? %>
    <h3> Participação nos filmes:</h3>
    <ul>
      <% actor.movies.each do |movie| %>
        <li> <strong> <%= movie.title %> </strong> </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/actors/_form.html.erb
<%= form_with(model: actor) do |form| %>
  <% if actor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Nome", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :birth_date,"Ano de Nascimento", style: "display: block" %>
    <%= form.text_field :birth_date %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editando ator</h1>

<%= render "form", actor: @actor %>

<br>

<div>
  <%= link_to "Exibir detalhes do ator", @actor %> |
  <%= link_to "Voltar para lista de atores", actors_path %>
</div>

app/views/actors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Atores</h1>

<div id="actors">
  <% @actors.each do |actor| %>
    <%= render actor %>
    <p>
      <%= link_to "Exibir detalhes do ator", actor %>
    </p>
  <% end %>
</div>

<%= link_to "Adicionar Ator", new_actor_path %>

app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render "form", actor: @actor %>

<br>

<div>
  <%= link_to "Back to actors", actors_path %>
</div>

app/views/actors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @actor %>

<div>
  <%= link_to "Editar ator", edit_actor_path(@actor) %> |
  <%= link_to "Voltar para lista de atores", actors_path %>

  <%= button_to "Deletar ator", @actor, method: :delete %>
</div>

app/views/casts/_cast.html.erb
<div id="<%= dom_id cast %>">
  <p>
    <strong>Movie:</strong>
    <%= cast.movie_id %>
  </p>

  <p>
    <strong>Actor:</strong>
    <%= cast.actor_id %>
  </p>

</div>

app/views/casts/_form.html.erb
<%= form_with(model: cast) do |form| %>
  <% if cast.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cast.errors.count, "error") %> prohibited this cast from being saved:</h2>

      <ul>
        <% cast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :movie_id, style: "display: block" %>
    <%= form.text_field :movie_id %>
  </div>

  <div>
    <%= form.label :actor_id, style: "display: block" %>
    <%= form.text_field :actor_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/casts/edit.html.erb
<h1>Editing cast</h1>

<%= render "form", cast: @cast %>

<br>

<div>
  <%= link_to "Show this cast", @cast %> |
  <%= link_to "Back to casts", casts_path %>
</div>

app/views/casts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Casts</h1>

<div id="casts">
  <% @casts.each do |cast| %>
    <%= render cast %>
    <p>
      <%= link_to "Show this cast", cast %>
    </p>
  <% end %>
</div>

<%= link_to "New cast", new_cast_path %>

app/views/casts/new.html.erb
<h1>New cast</h1>

<%= render "form", cast: @cast %>

<br>

<div>
  <%= link_to "Back to casts", casts_path %>
</div>

app/views/casts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cast %>

<div>
  <%= link_to "Edit this cast", edit_cast_path(@cast) %> |
  <%= link_to "Back to casts", casts_path %>

  <%= button_to "Destroy this cast", @cast, method: :delete %>
</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Comentário:</strong>
    <%= comment.text %>
  </p>

  <p>
    <strong>Filme:</strong>
    <%= comment.movie.title %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, "Crítica", style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.label :movie_id, "Filme", style: "display: block" %>
    <%= form.select :movie_id, @movies.pluck(:title, :id) %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comentários</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "Adicionar comentário", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Back to comments", comments_path %>
  <%= form_with(model: @comment) do |form| %>
    <%= form.hidden_field :status, value: true %>   
    <%= form.submit "Aprovar Comentário"%>
  <% end %>
</div>

app/views/layouts/_menu.html.erb
<header>
    <nav>
        <p><%= link_to "Filmes", movies_path %></p>
        <p><%= link_to "Atores", actors_path %></p>
        <p><%= link_to "Comentários para Aprovação", comments_path %></p>
        <p><%= link_to "Exibir Logs de comentários", logs_path %></p>
    </nav>
 </header>
<style>
    nav {
        display:flex;
        gap:2rem;
        background-color:#D2B4DE;
        padding:0 1rem;
    }
    nav p > a{
         text-decoration: none;
         color: #900C3F ;
    }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catálogo de Filmes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>
<style>
body{
  margin: 0 auto;
  background-color:#F5EEF8;
}
.content{
  padding: 1rem;
  color: #273746;
}
h1,h2,h3,h4,h5{
  
}
</style>

app/views/logs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Logs</h1>

<div id="logs">
   <% @logs.each do |log| %>
        <div>
            <p> <strong> Comentário:</strong> <%= log.comment.text.truncate(40)%></p>
            <ul>
                <li> 
                    <p> Aprovado na data:
                        <%= log.approved_date %>
                    <p>
                </li>
                <li>
                <p> Comentário do filme:
                    <%= log.comment.movie.title %>
                </p>
                </li>
            </ul>
        </div>
    <% end %>
</div>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :release_year, style: "display: block" %>
    <%= form.text_field :release_year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
     <strong>Titulo do Filme:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Ano de Lançamento:</strong>
    <%= movie.release_year %>
  </p>
  
  <p>
    <strong>Elenco de atores:</strong>
    <ul>
      <% movie.actors.each do |actor|%>
        <li> <%= actor.name %> </li>
      <% end %>
    </ul>
  </p>
  <% if @available_actors.present? %>
    <%= form_with url: add_actor_to_cast_path, method: :post do |form| %>
      <%= form.select :actor_id, @available_actors.pluck(:name  , :id) %>
      <%= form.hidden_field :id, value: @movie.id %>  
      <%= form.submit "Adicionar novo ator ao Elenco"%>
    <% end %>
  <% end %>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Filmes</h1>
<%= link_to "Adicionar novo Filme", new_movie_path %>  

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Detalhes do Filme", movie %>
    </p>
  <% end %>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<h2> Detalhes do Filme </h3>
<%= render @movie %>

<h3> Comentários do Filme: </h3>
<% @movie.comments.approved.each_with_index do |comment, index| %>
  <h4> Comentário n°<%= index %>: </h4>
  <p> <%= comment.text %> </p>
<% end %>

<div>
  <p> <%= link_to "Editar este filme", edit_movie_path(@movie) %> </p>
  <p> <%= link_to "Voltar para a seção de filmes", movies_path %> </p>
  <p> <%= button_to "Apagar este filme", @movie, method: :delete %> </p>
</div>